name: Git Commit Comment Linter
on:
  push:
    branches:
      - "*"

jobs:
  Check-Git-Commit-Message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (minimal)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Lint commit message
        run: |
          if [[ ! $(git log -1 --pretty=%B) =~ ^(feat|fix|chore|docs|style|refactor|test|perf):\ .{1,72}$ ]]; then
            echo "❌ Invalid commit message. Please use the conventional commit format."
            echo "   Example formats:"
            echo "     feat: add new feature"
            echo "     fix: resolve issue with login"
            echo "     chore: update dependencies"
            echo ""
            echo "To fix this issue, you can amend your commit message:"
            echo "   git commit --amend -m \"<type>: <description>\""
            echo "Then, force push the changes:"
            echo "   git push --force"
            exit 1
          fi
